/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb77b",
        "primary": "#a13924",
        "background": "#fff8f6",
        "primary-fixed-dim": "#ffb4a4",
        "on-primary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#a53b26",
        "on-tertiary-container": "#f3fffe",
        "on-background": "#241917",
        "on-error": "#ffffff",
        "surface-container-high": "#f9e3df",
        "primary-fixed": "#ffdad3",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#004f4f",
        "secondary-container": "#ffac62",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#8ff3f2",
        "on-secondary-fixed": "#2e1500",
        "on-tertiary-fixed": "#002020",
        "inverse-on-surface": "#ffede9",
        "surface-container-highest": "#f3ded9",
        "surface-container-low": "#fff0ee",
        "on-secondary": "#ffffff",
        "on-surface": "#241917",
        "primary-container": "#c25139",
        "inverse-surface": "#3a2d2b",
        "on-primary-fixed": "#3e0500",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#6d3a00",
        "on-secondary-container": "#763f00",
        "tertiary-fixed-dim": "#72d6d6",
        "inverse-primary": "#ffb4a4",
        "outline": "#8b716c",
        "on-surface-variant": "#57423d",
        "on-primary-fixed-variant": "#842411",
        "surface-dim": "#ebd5d1",
        "outline-variant": "#dec0ba",
        "surface-bright": "#fff8f6",
        "surface-container": "#ffe9e5",
        "secondary-fixed": "#ffdcc2",
        "surface-variant": "#f3ded9",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#fff8f6",
        "tertiary": "#006767",
        "tertiary-container": "#008282",
        "secondary": "#8e4e08"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-max": "1200px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-xl": ["Outfit"],
        "headline-lg": ["Outfit"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Outfit"],
        "headline-lg-mobile": ["Outfit"]
      },
      fontSize: {
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
